name: Release

on:
  push:
    branches:
      - 0.11-master
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64 g++-mingw-w64 automake autoconf libtool make git curl unzip zip

      - name: Build 32-bit (w32)
        run: |
          ./build.sh -clean
          mkdir -p package/w32
          cp -r output/* package/w32/
          cd package
          zip -r openocd-w32.zip w32/
          cd ..
          rm -rf output/*

      - name: Build 64-bit (w64)
        run: |
          ./build.sh -w64 -clean
          mkdir -p package/w64
          cp -r output/* package/w64/
          cd package
          zip -r openocd-w64.zip w64/
          cd ..

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openocd-windows-builds
          path: |
            package/openocd-w32.zip
            package/openocd-w64.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            package/openocd-w32.zip
            package/openocd-w64.zip
